export const LOGIN_USER = "LOGIN_USER";
export const AUTH_USER = "AUTH_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const RESET_EMPTY_USER = "RESET_EMPTY_USER";
export const LOAD_USER_DETAIL = "LOAD_USER_DETAIL";
export const SET_USER_PROPERTY = "SET_USER_PROPERTY";
export const EDIT_USER = "EDIT_USER";
export const ERR_USER = "ERR_USER";

export const RESET_EMPTY_EVENT = "RESET_EMPTY_EVENT";
export const LOAD_EVENT_LIST = "LOAD_EVENT_LIST";
export const LOAD_EVENT_DETAIL = "LOAD_EVENT_DETAIL";
export const SET_EVENT_TITLE = "SET_EVENT_TITLE";
export const SET_EVENT_DESCRIPTION = "SET_EVENT_DESCRIPTION";
export const ADD_EVENT_QUESTION = "ADD_EVENT_QUESTION";
export const MOVE_EVENT_QUESTION = "MOVE_EVENT_QUESTION";
export const UPDATE_EVENT_QUESTION = "UPDATE_EVENT_QUESTION";
export const DELETE_EVENT_QUESTION = "DELETE_EVENT_QUESTION";
export const SET_EVENT_START_DATE = "SET_EVENT_START_DATE";
export const SET_EVENT_END_DATE = "SET_EVENT_END_DATE";
export const SET_EVENT_NO_LIMIT_DATE = "SET_EVENT_NO_LIMIT_DATE";
export const SET_EVENT_OPTION_CD = "SET_EVENT_OPTION_CD";
export const EDIT_EVENT = "EDIT_EVENT";
export const ERR_EVENT = "ERR_EVENT";
export const ERR_EVENT_NO_RESET = "ERR_EVENT_NO_RESET";

// EVENT_ANSWER: 답변 전체 정보(작성일, 결과 등) 포괄
// ANSWER: 작성자 선택 답변 정보
export const RESET_EMPTY_EVENT_ANSWER_LIST = "RESET_EMPTY_EVENT_ANSWER_LIST";
export const LOAD_EVENT_ANSWER_LIST = "LOAD_EVENT_ANSWER_LIST";
export const LOAD_EVENT_ANSWER_DETAIL = "LOAD_EVENT_ANSWER_DETAIL";
export const EDIT_EVENT_ANSWER = "EDIT_EVENT_ANSWER";
export const SET_EVENT_ANSWER = "SET_EVENT_ANSWER";

export const RESET_EMPTY_NOTICE_LIST = "RESET_EMPTY_NOTICE_LIST";
export const RESET_EMPTY_NOTICE = "RESET_EMPTY_NOTICE";
export const LOAD_NOTICE_LIST = "LOAD_NOTICE_LIST";
export const SET_NOTICE = "SET_NOTICE";
export const SET_NOTICE_TITLE = "SET_NOTICE_TITLE";
export const SET_NOTICE_DESCRIPTION = "SET_NOTICE_DESCRIPTION";
export const SET_NOTICE_TARGET = "SET_NOTICE_TARGET";
export const EDIT_NOTICE = "EDIT_NOTICE";
