export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const AUTH_USER = 'AUTH_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const MYPAGE_USER = 'MYPAGE_USER';
export const MYPAGE_USER_EDIT = 'MYPAGE_USER_EDIT';

export const LOAD_EVENT_LIST = 'LOAD_EVENT_LIST';
export const LOAD_EVENT_DETAIL = 'LOAD_EVENT_DETAIL';
export const RESET_EMPTY_EVENT = 'RESET_EMPTY_EVENT';
export const SET_EVENT_TITLE = 'SET_EVENT_TITLE';
export const SET_EVENT_DESCRIPTION = 'SET_EVENT_DESCRIPTION';
export const ADD_EVENT_QUESTION = 'ADD_EVENT_QUESTION';
export const MOVE_EVENT_QUESTION = 'MOVE_EVENT_QUESTION';
export const UPDATE_EVENT_QUESTION = 'UPDATE_EVENT_QUESTION';
export const DELETE_EVENT_QUESTION = 'DELETE_EVENT_QUESTION';
export const SET_EVENT_START_DATE = 'SET_EVENT_START_DATE';
export const SET_EVENT_END_DATE = 'SET_EVENT_END_DATE';
export const SET_EVENT_NO_LIMIT_DATE = 'SET_EVENT_NO_LIMIT_DATE';
export const SET_EVENT_OPTION_CD = 'SET_EVENT_OPTION_CD';
export const ERR_EVENT = 'ERR_EVENT';
export const UPLOAD_EVENT = 'UPLOAD_EVENT';

export const LOAD_EVENT_ANSWER_LIST = 'LOAD_EVENT_ANSWER_LIST';

export const LOAD_NOTICE_LIST = 'LOAD_NOTICE_LIST';
export const SET_NOTICE = 'SET_NOTICE';
export const SET_NOTICE_TITLE = 'SET_NOTICE_TITLE';
export const SET_NOTICE_DESCRIPTION = 'SET_NOTICE_DESCRIPTION';
export const SET_NOTICE_TARGET = 'SET_NOTICE_TARGET';


export const SET_USER_EVENT_JOIN='set_user_evnet_join';

export const USER_ANSWER='user_answer';